// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');

require('./templates');


var App = window.App = require('./app');



App.NewController = require('./controllers/new_controller');
App.GameController = require('./controllers/game_controller');
App.GameListController = require('./controllers/game_list_controller');
App.GameList = require('./models/game_list');
App.Offer = require('./models/offer');
App.Card = require('./models/card');
App.Friend = require('./models/friend');
App.Game = require('./models/game');
App.NewRoute = require('./routes/new_route');
App.GameRoute = require('./routes/game_route');
App.GameListRoute = require('./routes/game_list_route');
App.OfferView = require('./views/offer_view');
App.CardView = require('./views/card_view');
App.FriendThumbView = require('./views/friend_thumb_view');
App.HexView = require('./views/hex_view');

require('./routes');

