// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');

require('./templates');


var App = window.App = require('./app');



App.Friend = require('./models/friend');
App.Game = require('./models/game');
App.NewRoute = require('./routes/new_route');

require('./routes');

